apiVersion: v1
kind: Service
metadata:
  name: pytorch-distributed-workers
spec:
  clusterIP: None  # Headless service
  selector:
    volcano.sh/job-name: pytorch-distributed  # Match the job name
  ports:
    - port: 29500
      name: distributed